version: '3.1'

services:

  backendsingle:
    build: ./api-server
    restart: always
    environment:
      PORT: 7070
    ports:
      - "8084:7070"

  loadbalancersingle:
    image: nginx:alpine
    restart: always
    ports:
      - 8085:80
    depends_on:
      - backendsingle

    volumes:
      # - ./data:/srv
      - ./nginx-single.conf:/etc/nginx/conf.d/default.conf