version: '3.1'

services:

  backend1:
    build: ./api-server
    restart: always
    environment:
      PORT: 7070
    ports:
      - "7071:7070"

  backend2:
    build: ./api-server
    restart: always
    environment:
      PORT: 7070
    ports:
      - "7072:7070"

  backend3:
    build: ./api-server
    restart: always
    environment:
      PORT: 7070
    ports:
      - "7073:7070"

  # loadbalancer:
  #   image: nginx
  #   ports:
  #     - "7070:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend1
  #     - backend2
  #     - backend3

  loadbalancer:
    image: nginx:alpine
    restart: always
    ports:
      - 7070:80
    depends_on:
      - backend1
      - backend2
      - backend3
    volumes:
      # - ./data:/srv
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "4.0"
    #       memory: 16G