version: '3.1'

services:

  backend1:
    build: ./api-server
    restart: always
    environment:
      PORT: 7070
    ports:
      - "7071:7070"

  backend2:
    build: ./api-server
    restart: always
    environment:
      PORT: 7070
    ports:
      - "7072:7070"

  backend3:
    build: ./api-server
    restart: always
    environment:
      PORT: 7070
    ports:
      - "7073:7070"

  loadbalancer:
    image: nginx:alpine
    restart: always
    ports:
      - 7070:80
    depends_on:
      - backend1
      - backend2
      - backend3
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf